// <auto-generated />
using System;
using AddressBookAPI.Entity.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddressBookAPI.Migrations
{
    [DbContext(typeof(AddressBookContext))]
    [Migration("20221220055905_new1")]
    partial class new1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AddressBookAPI.Entity.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Country")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Line1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RefTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zipcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RefTermId");

                    b.HasIndex("UserId");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "vizag",
                            Country = new Guid("ee3f90cd-2d51-40e8-a25b-f7c81f8e76b2"),
                            Line1 = "s-1",
                            Line2 = "s2",
                            RefTermId = new Guid("f87b8232-f2d8-4286-ac13-422aa54194ce"),
                            StateName = "AndhraPradesh",
                            UserId = new Guid("0fe5e908-cbd9-4c92-8445-32af3b939917"),
                            Zipcode = "531116"
                        });
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Field")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AssetDTO");
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RefTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RefTermId");

                    b.HasIndex("UserId");

                    b.ToTable("Email");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "psuryaraju5@gmail.com",
                            RefTermId = new Guid("f87b8232-f2d8-4286-ac13-422aa54194ce"),
                            UserId = new Guid("0fe5e908-cbd9-4c92-8445-32af3b939917")
                        });
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RefTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RefTermId");

                    b.HasIndex("UserId");

                    b.ToTable("Phone");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhoneNumber = "8142255769",
                            RefTermId = new Guid("f87b8232-f2d8-4286-ac13-422aa54194ce"),
                            UserId = new Guid("0fe5e908-cbd9-4c92-8445-32af3b939917")
                        });
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.RefSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefSet");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4005322-979c-4df5-96b2-16b2f6101006"),
                            Description = "email",
                            Key = "EMAIL_ADDRESS_TYPE"
                        },
                        new
                        {
                            Id = new Guid("9406dc1f-7781-4a7c-9f21-4d0267fb35d3"),
                            Description = "address ",
                            Key = "ADDRESS_TYPE"
                        },
                        new
                        {
                            Id = new Guid("1b484930-bf78-4b07-afef-6e9260f31e7b"),
                            Description = "country ",
                            Key = "COUNTRY"
                        },
                        new
                        {
                            Id = new Guid("c8dc949e-47f7-4eac-a83d-d0ebc8031300"),
                            Description = "phone",
                            Key = "PHONE_NUMBER_TYPE"
                        });
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.RefTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefTerm");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12cf7780-9096-4855-a049-40476cead362"),
                            Description = "work type",
                            Key = "WORK"
                        },
                        new
                        {
                            Id = new Guid("f87b8232-f2d8-4286-ac13-422aa54194ce"),
                            Description = "personal type",
                            Key = "PERSONAL"
                        },
                        new
                        {
                            Id = new Guid("04cd138d-6ce7-4389-919c-6687cf7f011f"),
                            Description = "alternate  type",
                            Key = "ALTERNATE"
                        },
                        new
                        {
                            Id = new Guid("ee3f90cd-2d51-40e8-a25b-f7c81f8e76b2"),
                            Description = "INDIA_TYPE",
                            Key = "INDIA"
                        },
                        new
                        {
                            Id = new Guid("7aae5636-8a33-4cbd-8fbf-09d7c143ed6b"),
                            Description = "USA_TYPE",
                            Key = "USA"
                        });
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.SetRefTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RefSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RefTermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RefSetId");

                    b.HasIndex("RefTermId");

                    b.ToTable("SetRefTerm");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cec21589-eb64-42a9-979a-1b603c771d1b"),
                            RefSetId = new Guid("b4005322-979c-4df5-96b2-16b2f6101006"),
                            RefTermId = new Guid("f87b8232-f2d8-4286-ac13-422aa54194ce")
                        },
                        new
                        {
                            Id = new Guid("c326884e-e132-43b6-9a7c-3c05bdbc750f"),
                            RefSetId = new Guid("b4005322-979c-4df5-96b2-16b2f6101006"),
                            RefTermId = new Guid("12cf7780-9096-4855-a049-40476cead362")
                        },
                        new
                        {
                            Id = new Guid("17d60ec1-722c-4063-83f6-595cd3a75247"),
                            RefSetId = new Guid("b4005322-979c-4df5-96b2-16b2f6101006"),
                            RefTermId = new Guid("04cd138d-6ce7-4389-919c-6687cf7f011f")
                        },
                        new
                        {
                            Id = new Guid("507a6c20-1a4a-425e-bafc-2ba01c939446"),
                            RefSetId = new Guid("9406dc1f-7781-4a7c-9f21-4d0267fb35d3"),
                            RefTermId = new Guid("f87b8232-f2d8-4286-ac13-422aa54194ce")
                        },
                        new
                        {
                            Id = new Guid("9fa96c0b-d4ba-4509-82a3-9b964058c241"),
                            RefSetId = new Guid("9406dc1f-7781-4a7c-9f21-4d0267fb35d3"),
                            RefTermId = new Guid("12cf7780-9096-4855-a049-40476cead362")
                        },
                        new
                        {
                            Id = new Guid("35ffaf42-d1fc-43c1-bd16-651cb70f5142"),
                            RefSetId = new Guid("9406dc1f-7781-4a7c-9f21-4d0267fb35d3"),
                            RefTermId = new Guid("04cd138d-6ce7-4389-919c-6687cf7f011f")
                        },
                        new
                        {
                            Id = new Guid("f9e010d3-4bb4-42da-80d6-a5ff46ad569f"),
                            RefSetId = new Guid("c8dc949e-47f7-4eac-a83d-d0ebc8031300"),
                            RefTermId = new Guid("f87b8232-f2d8-4286-ac13-422aa54194ce")
                        },
                        new
                        {
                            Id = new Guid("34a7e8e6-4dd5-4571-b4f8-8408d16df47e"),
                            RefSetId = new Guid("c8dc949e-47f7-4eac-a83d-d0ebc8031300"),
                            RefTermId = new Guid("12cf7780-9096-4855-a049-40476cead362")
                        },
                        new
                        {
                            Id = new Guid("7a63a47d-bcb8-43d5-a2d7-1c92430f6aad"),
                            RefSetId = new Guid("c8dc949e-47f7-4eac-a83d-d0ebc8031300"),
                            RefTermId = new Guid("04cd138d-6ce7-4389-919c-6687cf7f011f")
                        },
                        new
                        {
                            Id = new Guid("01ca30af-24c0-4cba-892a-ebce093251ff"),
                            RefSetId = new Guid("1b484930-bf78-4b07-afef-6e9260f31e7b"),
                            RefTermId = new Guid("ee3f90cd-2d51-40e8-a25b-f7c81f8e76b2")
                        },
                        new
                        {
                            Id = new Guid("a987948c-22f0-48ee-9893-5a5da65d4dd7"),
                            RefSetId = new Guid("1b484930-bf78-4b07-afef-6e9260f31e7b"),
                            RefTermId = new Guid("7aae5636-8a33-4cbd-8fbf-09d7c143ed6b")
                        });
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fe5e908-cbd9-4c92-8445-32af3b939917"),
                            FirstName = "surya",
                            LastName = "raju"
                        });
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.Address", b =>
                {
                    b.HasOne("AddressBookAPI.Entity.Models.RefTerm", "RefTerm")
                        .WithMany()
                        .HasForeignKey("RefTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AddressBookAPI.Entity.Models.User", "User")
                        .WithMany("Address")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.Asset", b =>
                {
                    b.HasOne("AddressBookAPI.Entity.Models.User", null)
                        .WithMany("Assetdto")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.Email", b =>
                {
                    b.HasOne("AddressBookAPI.Entity.Models.RefTerm", "refTerm")
                        .WithMany()
                        .HasForeignKey("RefTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AddressBookAPI.Entity.Models.User", "user")
                        .WithMany("Email")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.Phone", b =>
                {
                    b.HasOne("AddressBookAPI.Entity.Models.RefTerm", "RefTerm")
                        .WithMany()
                        .HasForeignKey("RefTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AddressBookAPI.Entity.Models.User", "User")
                        .WithMany("Phone")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AddressBookAPI.Entity.Models.SetRefTerm", b =>
                {
                    b.HasOne("AddressBookAPI.Entity.Models.RefSet", "RefSet")
                        .WithMany()
                        .HasForeignKey("RefSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AddressBookAPI.Entity.Models.RefTerm", "RefTerm")
                        .WithMany()
                        .HasForeignKey("RefTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
